- type: rank
  id: RMCRankMarineCommandant
  name: Комендант Корпуса Морской Пехоты
  prefix: ККМП
  paygrade: O10S

- type: rank
  id: RMCRankAssistantCommandant
  name: Помощник Коменданта Корпуса Морской Пехоты
  prefix: ПККМП
  paygrade: O10C

- type: rank
  id: RMCRankGeneral
  name: Генерал
  prefix: Ген.
  paygrade: O10

- type: rank
  id: RMCRankLieutenantGeneral
  name: Генерал Лейтенант
  prefix: Генерал Лейтенант
  paygrade: O9

- type: rank
  id: RMCRankMajorGeneral
  name: Генерал Майор
  prefix: Ген. Майор
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: Бригадный Генерал
  prefix: Бриг. Ген.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: Подполковник
  prefix: Подполк.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: Майор
  prefix: Майор
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: Капитан
  prefix: Капитан
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: Старший Лейтенант
  prefix: Ст. Лейт.
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: Младший Лейтенант
  prefix: Мл. Лейт.
  paygrade: O1
