using System.Linq;
using Content.Client._Stories.Players.JobWhitelist;
using Content.Client._Stories.Sponsors;
using Content.Client._Stories.TTS;
using Content.Client.Humanoid;
using Content.Client.Inventory;
using Content.Client.Lobby;
using Content.Shared._RMC14.Clothing;
using Content.Shared._RMC14.NamedItems;
using Content.Shared._Stories.Hunter;
using Content.Shared._Stories.Hunter.Profiles;
using Content.Shared._Stories.Hunter.Prototypes;
using Content.Shared._Stories.SCCVars;
using Content.Shared._Stories.TTS;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Containers;
using Robust.Shared.Enums;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Direction = Robust.Shared.Maths.Direction;
using Rope = Robust.Shared.Utility.Rope;

namespace Content.Client._Stories.Hunter.Profiles.UI;

[GenerateTypedNameReferences]
public sealed partial class HunterProfileEditor : Control
{
    private readonly Dictionary<string, Dictionary<string, List<HunterGearPrototype>>> _categorizedGear = new();
    
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ClientInventorySystem _inventory;
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IClientPreferencesManager _prefsManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    private readonly SponsorsSystem _sponsorsSystem;

    private readonly Dictionary<int, bool> _statusAvailability = new();
    private readonly JobWhitelistSystem _whitelistSystem;
    private List<TTSVoicePrototype> _allVoices = new();

    private string _cachedFlavorText = "";
    private bool _isDirty;
    private EntProtoId _previewCapePrototype = "STHunterCapeFull";
    private EntityUid _previewDummy;
    private Direction _previewRotation = Direction.South;

    private HunterProfile? _profile;

    public HunterProfileEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _inventory = _entityManager.System<ClientInventorySystem>();

        _whitelistSystem = _entityManager.System<JobWhitelistSystem>();
        _sponsorsSystem = _entityManager.System<SponsorsSystem>();

        InitializeControls();
        InitializeCustomizationTabs();

        if (_cfg.GetCVar(SCCVars.TTSEnabled))
        {
            TTSContainer.Visible = true;
            VoiceLabel.Visible = true;
            InitializeVoice();
        }
    }

    public event Action? OnProfileChanged;

    private void InitializeControls()
    {
        NameEdit.OnTextChanged += _ => SetDirty();

        RandomizeNameButton.OnPressed += _ => RandomizeName();
        RandomizeCharacterButton.OnPressed += _ => RandomizeFull();

        GenderButton.OnItemSelected += OnGenderSelected;
        AgeEdit.OnTextChanged += _ => SetDirty();

        FlavorTextEdit.OnTextChanged += _ =>
        {
            SetDirty();
            if (FlavorTextEdit.TextRope != null)
                _cachedFlavorText = Rope.Collapse(FlavorTextEdit.TextRope);
            else
                _cachedFlavorText = "";
        };

        StatusButton.OnItemSelected += OnStatusSelected;

        SkinColor.OnColorChanged += _ =>
        {
            if (_profile != null)
                _profile.SkinColor = SkinColor.Color;
            SetDirty();
            UpdatePreview();
        };

        SaveButton.OnPressed += _ => Save();
        ShowClothesButton.OnToggled += _ => UpdatePreview();
        ShowCapeButton.OnToggled += _ => UpdatePreview();

        RotateLeftButton.OnPressed += _ =>
        {
            _previewRotation = RotateDirection(_previewRotation, false);
            SpriteView.OverrideDirection = _previewRotation;
        };

        RotateRightButton.OnPressed += _ =>
        {
            _previewRotation = RotateDirection(_previewRotation, true);
            SpriteView.OverrideDirection = _previewRotation;
        };

        GenderButton.AddItem(
            Loc.GetString("humanoid-profile-editor-pronouns-male-text"),
            (int)Gender.Male
        );
        GenderButton.AddItem(
            Loc.GetString("humanoid-profile-editor-pronouns-female-text"),
            (int)Gender.Female
        );

        PopulateStatusButton();

        foreach (var style in Enum.GetValues<HunterSoundStyle>())
        {
            var text = Loc.GetString($"st-hunter-style-{style.ToString().ToLower()}");
            TranslatorStyleButton.AddItem(text, (int)style);
            CloakStyleButton.AddItem(text, (int)style);
        }

        TranslatorStyleButton.OnItemSelected += args =>
        {
            TranslatorStyleButton.SelectId(args.Id);
            if (_profile != null)
                _profile.TranslatorSound = (HunterSoundStyle)args.Id;
            SetDirty();
        };

        CloakStyleButton.OnItemSelected += args =>
        {
            CloakStyleButton.SelectId(args.Id);
            if (_profile != null)
                _profile.CloakSound = (HunterSoundStyle)args.Id;
            SetDirty();
        };

        CapeColorSelector.OnColorChanged += _ =>
        {
            if (_profile != null)
                _profile.CapeColor = CapeColorSelector.Color;
            SetDirty();
            UpdatePreview();
        };
    }

    private void PopulateStatusButton()
    {
        StatusButton.Clear();
        _statusAvailability.Clear();

        var canNormal = _whitelistSystem.IsWhitelisted("STHunter");
        var canCouncil = _whitelistSystem.IsWhitelisted("STHunterCouncil");
        var canLeader = _whitelistSystem.IsWhitelisted("STHunterLeader");

        if (_sponsorsSystem.TryGetInfo(out var sponsorInfo) && sponsorInfo.CanPlayHunter)
        {
            if (sponsorInfo.MaxHunterStatus >= HunterStatus.Normal)
                canNormal = true;
            if (sponsorInfo.MaxHunterStatus >= HunterStatus.Council)
                canCouncil = true;
            if (sponsorInfo.MaxHunterStatus >= HunterStatus.Leader)
                canLeader = true;
        }

        _statusAvailability[(int)HunterStatus.Normal] = canNormal;
        _statusAvailability[(int)HunterStatus.Council] = canCouncil;
        _statusAvailability[(int)HunterStatus.Leader] = canLeader;

        void AddStatusItem(HunterStatus status)
        {
            var id = (int)status;
            var isAvailable = _statusAvailability[id];

            if (!isAvailable)
                return;

            var nameKey = $"st-hunter-status-{status.ToString().ToLower()}";
            var name = Loc.GetString(nameKey);

            StatusButton.AddItem(name, id);
        }

        AddStatusItem(HunterStatus.Normal);
        AddStatusItem(HunterStatus.Council);
        AddStatusItem(HunterStatus.Leader);
    }

    private void OnStatusSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_profile == null)
            return;

        StatusButton.SelectId(args.Id);
        _profile.Status = (HunterStatus)args.Id;
        SetDirty();
    }

    private void InitializeVoice()
    {
        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(v => v.RoundStart)
            .OrderBy(v => v.Name)
            .ToList();

        VoiceButton.OnItemSelected += args =>
        {
            VoiceButton.SelectId(args.Id);
            if (_profile != null && args.Id >= 0 && args.Id < _allVoices.Count)
            {
                var voiceProto = _allVoices[args.Id];
                if (voiceProto != null)
                    _profile.Voice = voiceProto.ID;
            }

            SetDirty();
        };

        VoicePlayButton.OnPressed += _ =>
        {
            if (_profile == null)
                return;
            var sys = _entityManager.System<TTSSystem>();
            sys.RequestPreviewTTS(_profile.Voice, true);
        };
    }

    private void UpdateVoiceSelection()
    {
        if (_profile == null)
            return;

        VoiceButton.Clear();
        var sex = _profile.Gender == Gender.Male ? Sex.Male : Sex.Female;
        var selectedListIndex = -1;

        for (var i = 0; i < _allVoices.Count; i++)
        {
            var v = _allVoices[i];

            if (v.Blacklist != null && v.Blacklist.Contains("Hunter"))
                continue;

            if (v.Sex == sex || v.Sex == Sex.Unsexed)
            {
                VoiceButton.AddItem(v.Name, i);
                if (v.ID == _profile.Voice)
                    selectedListIndex = i;
            }
        }

        if (selectedListIndex == -1)
        {
            for (var i = 0; i < _allVoices.Count; i++)
            {
                var v = _allVoices[i];
                var blocked = v.Blacklist != null && v.Blacklist.Contains("Hunter");
                if (!blocked && (v.Sex == sex || v.Sex == Sex.Unsexed))
                {
                    _profile.Voice = v.ID;
                    selectedListIndex = i;
                    break;
                }
            }
        }

        if (selectedListIndex != -1)
            VoiceButton.SelectId(selectedListIndex);
    }

    private Direction RotateDirection(Direction dir, bool clockwise)
    {
        var d = (int)dir;
        if (clockwise)
            d = (d + 2) % 8;
        else
            d = (d - 2 + 8) % 8;

        return (Direction)d;
    }

    private void InitializeCustomizationTabs()
    {
        EquipmentTabs.SetTabTitle(0, Loc.GetString("st-hunter-profile-editor-armor-tab"));
        EquipmentTabs.SetTabTitle(1, Loc.GetString("st-hunter-profile-editor-mask-tab"));
        EquipmentTabs.SetTabTitle(2, Loc.GetString("st-hunter-profile-editor-accessory-tab"));
        EquipmentTabs.SetTabTitle(3, Loc.GetString("st-hunter-profile-editor-greaves-tab"));
        EquipmentTabs.SetTabTitle(4, Loc.GetString("st-hunter-profile-editor-cape-tab"));
        EquipmentTabs.SetTabTitle(5, Loc.GetString("st-hunter-profile-editor-caster-tab"));
        EquipmentTabs.SetTabTitle(6, Loc.GetString("st-hunter-profile-editor-bracer-tab"));

        var quillPicker = new SingleMarkingPicker { Category = MarkingCategories.Hair };
        quillPicker.OnMarkingSelect += OnQuillSelected;
        quillPicker.OnColorChanged += _ => UpdatePreview();
        QuillsContent.AddChild(quillPicker);

        var gearTabs = new Dictionary<string, Control>
        {
            { "Armor", ArmorTab },
            { "Mask", MaskTab },
            { "Accessory", AccessoryTab },
            { "Greaves", GreavesTab },
            { "Cape", CapeTab },
            { "Caster", CasterTab },
            { "Bracer", BracerTab }
        };

        var isSponsor = _sponsorsSystem.TryGetInfo(out var sponsorInfo) && sponsorInfo.CanUseHunterCustomization;

        _categorizedGear.Clear();
        foreach (var gearProto in _prototypeManager.EnumeratePrototypes<HunterGearPrototype>())
        {
            if (!_categorizedGear.ContainsKey(gearProto.Category))
                _categorizedGear[gearProto.Category] = new Dictionary<string, List<HunterGearPrototype>>();

            if (!_categorizedGear[gearProto.Category].ContainsKey(gearProto.Material))
                _categorizedGear[gearProto.Category][gearProto.Material] = new List<HunterGearPrototype>();

            _categorizedGear[gearProto.Category][gearProto.Material].Add(gearProto);
        }

        foreach (var (category, materials) in _categorizedGear)
        {
            if (!gearTabs.TryGetValue(category, out var tab))
                continue;

            tab.DisposeAllChildren();

            if (materials.Count > 1)
            {
                var splitContainer = new SplitContainer
                {
                    Orientation = SplitContainer.SplitOrientation.Horizontal,
                    VerticalExpand = true,
                    HorizontalExpand = true,
                    State = SplitContainer.SplitState.Auto,
                };

                var materialListScroll = new ScrollContainer
                {
                    VerticalExpand = true,
                    HorizontalExpand = false,
                    MinWidth = 120,
                    HScrollEnabled = false
                };
                var materialListContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                    Margin = new Thickness(0, 0, 5, 0)
                };
                materialListScroll.AddChild(materialListContainer);

                var pickerArea = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                    HorizontalExpand = true
                };

                void PopulatePicker(string materialName)
                {
                    pickerArea.DisposeAllChildren();
                    if (!materials.TryGetValue(materialName, out var gears)) return;

                    var picker = new SpritePicker();
                    picker.Populate(gears, isSponsor);

                    if (category == "Accessory")
                        picker.AddCustomButton("Nothing", Loc.GetString("st-hunter-gear-none"), false, true);

                    picker.OnSelectionChanged += protoId => OnSpriteSelected(category, protoId);
                    pickerArea.AddChild(picker);
                }

                var materialButtonGroup = new ButtonGroup();
                string? firstMaterial = null;

                foreach (var material in materials.Keys.OrderBy(k => k))
                {
                    firstMaterial ??= material;
                    
                    var matKey = $"st-hunter-material-{material.ToLowerInvariant()}";
                    var locTitle = Loc.GetString(matKey);
                    if (locTitle.StartsWith("st-hunter-material-"))
                        locTitle = material;

                    var btn = new Button
                    {
                        Text = locTitle,
                        ToggleMode = true,
                        Group = materialButtonGroup,
                        TextAlign = Label.AlignMode.Left
                    };
                    btn.OnPressed += _ => PopulatePicker(material);
                    materialListContainer.AddChild(btn);
                }

                splitContainer.AddChild(materialListScroll);
                splitContainer.AddChild(pickerArea);
                tab.AddChild(splitContainer);

                if (firstMaterial != null)
                {
                    PopulatePicker(firstMaterial);
                    if (materialListContainer.ChildCount > 0 && materialListContainer.GetChild(0) is Button firstBtn)
                        firstBtn.Pressed = true;
                }
            }
            else if (materials.Count == 1)
            {
                var gears = materials.First().Value;
                var picker = new SpritePicker();
                
                picker.Populate(gears, isSponsor);

                if (category == "Accessory")
                {
                    picker.AddCustomButton("Nothing", Loc.GetString("st-hunter-gear-none"), false, true);
                }

                picker.OnSelectionChanged += protoId => OnSpriteSelected(category, protoId);
                tab.AddChild(picker);
            }
        }
    }

    private void RandomizeName()
    {
        if (_profile == null)
            return;

        var currentDesc = _cachedFlavorText;
        _profile.Name = HumanoidCharacterProfile.GetName("STHunter", _profile.Gender);
        UpdateControls();
        FlavorTextEdit.TextRope = new Rope.Leaf(currentDesc);
        SetDirty();
    }

    private void RandomizeFull()
    {
        if (_profile == null)
            return;

        var randomProfile = HunterProfile.Random(_prototypeManager, _random);
        var name = HumanoidCharacterProfile.GetName("STHunter", randomProfile.Gender);
        var currentDesc = _cachedFlavorText;

        _profile.Name = name;
        _profile.Gender = randomProfile.Gender;
        _profile.Age = randomProfile.Age;
        
        _profile.ArmorPrototype = randomProfile.ArmorPrototype;
        _profile.MaskPrototype = randomProfile.MaskPrototype;
        _profile.GreavesPrototype = randomProfile.GreavesPrototype;
        _profile.CasterPrototype = randomProfile.CasterPrototype;
        _profile.BracerPrototype = randomProfile.BracerPrototype;
        _profile.HeadAccessory = randomProfile.HeadAccessory;
        
        _profile.SkinColor = randomProfile.SkinColor;
        _profile.Voice = randomProfile.Voice;
        _profile.TranslatorSound = randomProfile.TranslatorSound;
        _profile.CloakSound = randomProfile.CloakSound;
        _profile.CapeColor = randomProfile.CapeColor;

        UpdateControls();
        FlavorTextEdit.TextRope = new Rope.Leaf(currentDesc);

        SetDirty();
        UpdatePreview();
    }

    private void OnSpriteSelected(string category, EntProtoId protoId)
    {
        if (_profile == null)
            return;

        switch (category)
        {
            case "Armor":
                _profile.ArmorPrototype = protoId;
                break;
            case "Mask":
                _profile.MaskPrototype = protoId;
                break;
            case "Greaves":
                _profile.GreavesPrototype = protoId;
                break;
            case "Caster":
                _profile.CasterPrototype = protoId;
                break;
            case "Bracer":
                _profile.BracerPrototype = protoId;
                break;
            case "Accessory":
                _profile.HeadAccessory = protoId;
                break;
            case "Cape":
                _previewCapePrototype = protoId;
                break;
        }

        SetDirty();
        UpdatePreview();
    }

    private void OnGenderSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_profile == null)
            return;
        GenderButton.SelectId(args.Id);
        _profile.Gender = (Gender)args.Id;

        UpdateVoiceSelection();
        SetDirty();
        UpdatePreview();
    }

    private void OnQuillSelected((int slot, string id) marking)
    {
        if (_profile == null)
            return;
        _profile.QuillMarkingId = new ProtoId<MarkingPrototype>(marking.id);
        SetDirty();
        UpdatePreview();
    }

    public void SetProfile(HunterProfile? profile)
    {
        _profile = profile?.Clone();
        PopulateStatusButton();
        UpdateControls();
        UpdatePreview();
        _isDirty = false;
        SaveButton.Disabled = true;
    }

    private void UpdateControls()
    {
        if (_profile == null)
            return;

        NameEdit.Text = _profile.Name;

        var genderId = (int)_profile.Gender;
        var genderValid = false;
        for (var i = 0; i < GenderButton.ItemCount; i++)
        {
            if (GenderButton.GetItemId(i) == genderId)
            {
                genderValid = true;
                break;
            }
        }
        if (!genderValid && GenderButton.ItemCount > 0)
        {
            genderId = GenderButton.GetItemId(0);
            _profile.Gender = (Gender)genderId;
            SetDirty();
        }
        if (genderValid || GenderButton.ItemCount > 0)
            GenderButton.SelectId(genderId);
        
        AgeEdit.Text = _profile.Age.ToString();

        _cachedFlavorText = _profile.FlavorText ?? "";
        FlavorTextEdit.TextRope = new Rope.Leaf(_cachedFlavorText);

        var statusId = (int)_profile.Status;

        if (StatusButton.ItemCount > 0)
        {
            var isStatusInList = false;
            for (int i = 0; i < StatusButton.ItemCount; i++)
            {
                if (StatusButton.GetItemId(i) == statusId)
                {
                    isStatusInList = true;
                    break;
                }
            }

            if (!isStatusInList)
            {
                var fallbackId = (int)HunterStatus.Normal;
                var normalInList = false;
                for (int i = 0; i < StatusButton.ItemCount; i++)
                {
                    if (StatusButton.GetItemId(i) == fallbackId)
                    {
                        normalInList = true;
                        break;
                    }
                }

                if (normalInList)
                    statusId = fallbackId;
                else
                    statusId = StatusButton.GetItemId(0);
            
                _profile.Status = (HunterStatus)statusId;
                SetDirty();
            }

            StatusButton.SelectId(statusId);
        }

        SkinColor.Color = _profile.SkinColor;

        if (QuillsContent.ChildCount > 0 && QuillsContent.GetChild(0) is SingleMarkingPicker quillPicker)
        {
            var hairColors = new List<Color> { _profile.SkinColor };
            string markingId = _profile.QuillMarkingId;
            if (string.IsNullOrEmpty(markingId))
                markingId = "HunterHairStandard";

            var hairMarking = new List<Shared.Humanoid.Markings.Marking> { new(markingId, hairColors) };
            quillPicker.UpdateData(hairMarking, "STHunter", 1);
        }

        UpdateVoiceSelection();

        var translatorId = (int)_profile.TranslatorSound;
        var translatorValid = false;
        for (var i = 0; i < TranslatorStyleButton.ItemCount; i++)
        {
            if (TranslatorStyleButton.GetItemId(i) == translatorId)
            {
                translatorValid = true;
                break;
            }
        }
        if (translatorValid)
            TranslatorStyleButton.SelectId(translatorId);
        else if (TranslatorStyleButton.ItemCount > 0)
            TranslatorStyleButton.SelectId(TranslatorStyleButton.GetItemId(0));

        var cloakId = (int)_profile.CloakSound;
        var cloakValid = false;
        for (var i = 0; i < CloakStyleButton.ItemCount; i++)
        {
            if (CloakStyleButton.GetItemId(i) == cloakId)
            {
                cloakValid = true;
                break;
            }
        }
        if (cloakValid)
            CloakStyleButton.SelectId(cloakId);
        else if (CloakStyleButton.ItemCount > 0)
            CloakStyleButton.SelectId(CloakStyleButton.GetItemId(0));
        
        CapeColorSelector.Color = _profile.CapeColor;

        SetPickerSelected("Armor", _profile.ArmorPrototype);
        SetPickerSelected("Mask", _profile.MaskPrototype);
        SetPickerSelected("Greaves", _profile.GreavesPrototype);
        SetPickerSelected("Caster", _profile.CasterPrototype);
        SetPickerSelected("Bracer", _profile.BracerPrototype);
        SetPickerSelected("Accessory", _profile.HeadAccessory);
        SetPickerSelected("Cape", _previewCapePrototype);
    }

    private void SetPickerSelected(string category, EntProtoId protoId)
    {
        Control? tab = category switch
        {
            "Armor" => ArmorTab,
            "Mask" => MaskTab,
            "Greaves" => GreavesTab,
            "Caster" => CasterTab,
            "Bracer" => BracerTab,
            "Accessory" => AccessoryTab,
            "Cape" => CapeTab,
            _ => null,
        };

        if (tab == null)
            return;

        void SelectInPicker(Control container)
        {
            if (container is SpritePicker picker)
            {
                picker.SetSelected(protoId);
                return;
            }
            if (container is BoxContainer box && box.ChildCount > 0 && box.GetChild(0) is SpritePicker innerPicker)
            {
                innerPicker.SetSelected(protoId);
                return;
            }
        }

        if (tab.ChildCount > 0 && tab.GetChild(0) is SplitContainer split)
        {
            if (!_categorizedGear.ContainsKey(category)) return;

            if (split.ChildCount < 2) return;

            var leftScroll = split.GetChild(0) as ScrollContainer;
            var rightArea = split.GetChild(1) as BoxContainer;

            if (leftScroll?.GetChild(0) is BoxContainer listContainer)
            {
                foreach (var (material, gears) in _categorizedGear[category])
                {
                    if (gears.Any(g => g.EntityProto == protoId))
                    {
                        int buttonIndex = -1;
                        var sortedMaterials = _categorizedGear[category].Keys.OrderBy(k => k).ToList();
                        buttonIndex = sortedMaterials.IndexOf(material);

                        if (buttonIndex >= 0 && buttonIndex < listContainer.ChildCount)
                        {
                            if (listContainer.GetChild(buttonIndex) is Button btn)
                            {
                                btn.Pressed = true;

                                rightArea?.DisposeAllChildren();
                                if (rightArea != null)
                                {
                                    var isSponsor = _sponsorsSystem.TryGetInfo(out var sponsorInfo) && sponsorInfo.CanUseHunterCustomization;
                                    var picker = new SpritePicker();
                                    picker.Populate(gears, isSponsor);
                                    if (category == "Accessory") picker.AddCustomButton("Nothing", Loc.GetString("st-hunter-gear-none"), false, true);
                                    
                                    picker.OnSelectionChanged += pid => OnSpriteSelected(category, pid);
                                    rightArea.AddChild(picker);
                                    picker.SetSelected(protoId);
                                }
                            }
                        }
                        return;
                    }
                }
            }
        }
        else if (tab.ChildCount > 0)
        {
            SelectInPicker(tab.GetChild(0));
        }
    }

    private void UpdatePreview()
    {
        if (_profile == null)
            return;

        _entityManager.DeleteEntity(_previewDummy);
        _previewDummy = _entityManager.SpawnEntity("STMobHunterDummy", MapCoordinates.Nullspace);

        var humanoidSystem = _entityManager.System<HumanoidAppearanceSystem>();
        var handsSystem = _entityManager.System<SharedHandsSystem>();

        var quillMarking = _profile.QuillMarkingId;
        if (!_prototypeManager.HasIndex(quillMarking))
            quillMarking = "HunterHairStandard";

        var appearance = new HumanoidCharacterAppearance(
            quillMarking,
            _profile.SkinColor,
            "NoFacialHair",
            Color.White,
            Color.Black,
            _profile.SkinColor,
            new List<Shared.Humanoid.Markings.Marking>()
        );

        var tempHumanoidProfile = new HumanoidCharacterProfile(
            _profile.Name,
            "",
            "STHunter",
            "",
            _profile.Age,
            _profile.Gender == Gender.Male ? Sex.Male : Sex.Female,
            _profile.Gender,
            appearance,
            SpawnPriorityPreference.None,
            ArmorPreference.Random,
            null,
            new Dictionary<ProtoId<JobPrototype>, JobPriority>(),
            PreferenceUnavailableMode.StayInLobby,
            new HashSet<ProtoId<AntagPrototype>>(),
            new HashSet<ProtoId<TraitPrototype>>(),
            new Dictionary<string, RoleLoadout>(),
            new SharedRMCNamedItems(),
            true,
            "",
            ""
        );

        humanoidSystem.LoadProfile(_previewDummy, tempHumanoidProfile);

        if (ShowClothesButton.Pressed)
        {
            void EquipIfValid(EntProtoId proto, string slot)
            {
                if (
                    !string.IsNullOrEmpty(proto)
                    && proto.Id != "Nothing"
                    && _prototypeManager.HasIndex<EntityPrototype>(proto)
                )
                {
                    _inventory.TryEquip(
                        _previewDummy,
                        _entityManager.SpawnEntity(proto, MapCoordinates.Nullspace),
                        slot,
                        true,
                        true
                    );
                }
            }

            EquipIfValid(_profile.BracerPrototype, "gloves");
            EquipIfValid(_profile.ArmorPrototype, "outerClothing");
            EquipIfValid(_profile.MaskPrototype, "mask");
            EquipIfValid(_profile.GreavesPrototype, "shoes");
            
            if (ShowCapeButton.Pressed)
                EquipIfValid(_previewCapePrototype, "back");

            if (_inventory.TryGetSlotEntity(_previewDummy, "mask", out var maskUid))
            {
                var containerSys = _entityManager.System<SharedContainerSystem>();
                if (
                    _entityManager.TryGetComponent<HelmetAccessoryHolderComponent>(maskUid, out var holder)
                    && containerSys.TryGetContainer(maskUid.Value, "helmet-accessory-container", out var container)
                )
                {
                    if (
                        !string.IsNullOrEmpty(_profile.HeadAccessory)
                        && _profile.HeadAccessory.Id != "Nothing"
                        && _prototypeManager.HasIndex<EntityPrototype>(_profile.HeadAccessory)
                    )
                    {
                        var accessory = _entityManager.SpawnEntity(_profile.HeadAccessory, MapCoordinates.Nullspace);
                        containerSys.Insert(accessory, container);
                    }
                }
            }

            if (ShowCapeButton.Pressed && _inventory.TryGetSlotEntity(_previewDummy, "back", out var capeUid))
            {
                _entityManager
                    .System<SharedAppearanceSystem>()
                    .SetData(capeUid.Value, HunterCapeVisuals.Color, _profile.CapeColor);
            }

            if (
                !string.IsNullOrEmpty(_profile.CasterPrototype)
                && _prototypeManager.HasIndex<EntityPrototype>(_profile.CasterPrototype)
            )
            {
                _entityManager.EnsureComponent<HandsComponent>(_previewDummy);
                var caster = _entityManager.SpawnEntity(_profile.CasterPrototype, MapCoordinates.Nullspace);
                if (!handsSystem.TryPickupAnyHand(_previewDummy, caster, false))
                    _entityManager.DeleteEntity(caster);
            }
        }

        SpriteView.SetEntity(_previewDummy);
        SpriteView.OverrideDirection = _previewRotation;
    }

    private void SetDirty()
    {
        _isDirty = true;
        SaveButton.Disabled = false;
    }

    private void Save()
    {
        if (_profile == null || !_isDirty)
            return;

        _profile.Name = NameEdit.Text;
        _profile.Gender = (Gender)GenderButton.SelectedId;

        if (int.TryParse(AgeEdit.Text, out var age))
            _profile.Age = Math.Clamp(age, 175, 3000);

        _profile.FlavorText = _cachedFlavorText;

        _profile.Status = (HunterStatus)StatusButton.SelectedId;
        _profile.SkinColor = SkinColor.Color;

        _prefsManager.UpdateHunterProfile(_profile.Clone());
        _isDirty = false;
        SaveButton.Disabled = true;
        OnProfileChanged?.Invoke();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _entityManager.DeleteEntity(_previewDummy);
    }
}
