- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Руководитель Специалист
  prefix: Рук. Спец.

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Старший Руководитель
  prefix: Ст. Рук.

- type: rank
  id: RMCRankWeYaExecutive
  name: Руководитель
  prefix: Рук.

- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Младший Руководитель
  prefix: Мл. Рук.
